import { Create ,  SimpleForm, required, TextInput, NumberInput, SelectInput, ReferenceInput} from "react-admin";

export const ChallengeCreate =()=>{
  return(
    <Create>
      <SimpleForm>
        <TextInput 
          source="question" 
          validate={[required()]} 
          label="Question" 
        />
        <SelectInput 
          source="type"
          choices={[
            {
              id:"SELECT",
              name:"SELECT",
            },
            {
              id:"ASSIST",
              name:"ASSIST",
            }
          ]}
          validate={[required()]} 
          optionText="name"
        />
        <ReferenceInput 
          source="lessonId"
          reference="lessons"
        />
        <NumberInput 
          source="order"
          validate={[required()]}
          label="Order"
        />
      </SimpleForm>
    </Create>
  )
}