import type { Metadata } from "next";
import { Nunito} from "next/font/google";
import { Toaster } from "sonner";
import "./globals.css";
import {
  ClerkProvider,
} from '@clerk/nextjs'
import { ExitModal } from "@/components/modal/exit-modal";

const font = Nunito({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={font.className}>
          <Toaster />
          <ExitModal />
          {children}
        </body>
      </html>
    </ClerkProvider>
  )
}